//THIS FILE IS GENERATED
#define CRTMPSERVER_VERSION_BUILD_DATE 1366188645
#define CRTMPSERVER_VERSION_BUILD_NUMBER "794M"
#define CRTMPSERVER_VERSION_RELEASE_NUMBER "1.1_beta"
#define CRTMPSERVER_VERSION_CODE_NAME "Gladiator"
#define CRTMPSERVER_VERSION_BUILDER_OS_NAME ""
#define CRTMPSERVER_VERSION_BUILDER_OS_VERSION ""
#define CRTMPSERVER_VERSION_BUILDER_OS_ARCH ""
#define CRTMPSERVER_VERSION_BUILDER_OS_UNAME "Darwin Rayteki-MacBook-Pro.local 11.4.2 Darwin Kernel Version 11.4.2: Thu Aug 23 16:25:48 PDT 2012; root:xnu-1699.32.7~1/RELEASE_X86_64 x86_64"
